Project4/config/routes.rb
Project4::Application.routes.draw do

  match '/photos/index/:id' => 'photos#index', :as => :photos

  root :to => 'users#index'

end

Project4/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :date_time

  belongs_to :photo
  belongs_to :user
end

Project4/app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date_time, :file_name

  belongs_to :user
  has_many :comments
end

Project4/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name

  has_many :photos
  has_many :comments
end

Project4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Project4/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @user = User.find(params[:id])
  end
end

Project4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

Project4/app/helpers/application_helper.rb
module ApplicationHelper
end

Project4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <p class="header__big">
      Bill Barnett<br />
      Gaslight
    </p>
    <p>bill@gaslight.co<br />
       (513) 470-3525<br />
       @agilous
    </p>
  </div>

  <%= yield %>

</body>
</html>

Project4/app/views/photos/index.html.erb
<h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
<% if @user.photos.count > 0 -%>
  <% @user.photos.each do |photo| -%>
    <div><%= image_tag(photo.file_name) %></div>
    <div>Created: <%= photo.date_time.localtime.strftime('%I:%M:%S %p on %B %e, %Y') %></div>
    <% if photo.comments.count > 0 -%>
      <div>Comments:</div>
      <% photo.comments.each do |comment| -%>
        <div>
          <%= comment.comment %><br />
          By: <%= link_to "#{comment.user.first_name} #{comment.user.last_name}", photos_path(comment.user) %><br />
          Posted: <%= comment.date_time.localtime.strftime('%l:%M:%S %p on %B %e, %Y') %>
        </div>
        <hr />
      <% end -%>
    <% else -%>
      <div>No comments (yet!)</div>
      <hr />
    <% end -%>
  <% end -%>
<% end -%>

<div><%= link_to "Back", root_path %></div>

Project4/app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| -%>
    <tr>
      <td><%= link_to "#{user.first_name} #{user.last_name}", photos_path(user.id) %></td>
    </tr>
    <% end -%>
  </tbody>