Project3/config/routes.rb
Project3::Application.routes.draw do

  match 'state/filter' => 'states#filter'

  match ':controller(/:action(/:id))(.:format)'
end

Project3/app/models/state.rb
class State
  @states = %w{ Alabama Alaska Arizona Arkansas California Colorado
                Connecticut Delaware Florida Georgia Hawaii Idaho
                Illinois Indiana Iowa Kansas Kentucky Louisiana Maine
                Maryland Massachusetts Michigan Minnesota Mississippi
                Missouri Montana Nebraska Nevada New\ Hampshire
                New\ Jersey New\ Mexico New\ York North\ Carolina
                North\ Dakota Ohio Oklahoma Oregon Pennsylvania
                Rhode\ Island South\ Carolina South\ Dakota Tennessee
                Texas Utah Vermont Virginia Washington West\ Virginia
                Wisconsin Wyoming }

  def self.filter(string)
    @states.select { |state| /#{string}/i =~ state }
  end
end

Project3/app/controllers/states_controller.rb
class StatesController < ApplicationController
  def filter
    @matching_states = (params[:substring] ? State.filter(params[:substring]) : nil)
    @substring = params[:substring]

    respond_to :html
  end
end

Project3/app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  def show2
    @tabs_1 = [ { label: "Inventory", url: "#Inventory" },
                { label: "Order Information", url: "#Order Information" },
                { label: "Accounts", url: "#Accounts" },
                { label: "Shippers", url: "#Shippers" },
                { label: "Suppliers", url: "#Suppliers" } ]

    @tabs_2 = [ { label: "Gaslight", url: "http://gaslight.co" },
                { label: "Neo", url: "http://www.neo.com/" },
                { label: "ThoughtWorks", url: "http://www.thoughtworks.com/" },
                { label: "Hashrocket", url: "http://hashrocket.com/" } ]
  end
end

Project3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <p class="header__big">
      Bill Barnett<br />
      Gaslight
    </p>
    <p>bill@gaslight.co<br />
       (513) 470-3525<br />
       @agilous
    </p>
  </div>

  <%= yield %>

</body>
</html>

Project3/app/views/states/filter.html.erb
<% if @matching_states && @matching_states.count > 0 -%>
  <p>The states listed below contain the substring &ldquo;<%= @substring %>&rdquo;.</p>
    <ol>
    <% @matching_states.each do |matching_state| -%>
      <li><%= matching_state %></li>
    <% end -%>
    </ol>
<% else -%>
  <% if @substring -%>
    <p>Sorry, no states matched the substring &ldquo;<%= @substring %>&rdquo;.</p>
  <% else -%>
    <p>Please supply a query parameter in the URL like this one:<br /><%= link_to "/state/filter?substring=oh", state_filter_path(substring: "oh") %></p>
  <% end -%>
<% end -%>

Project3/app/views/tabs/_tabs.html.erb
<div>
<% tabs.each do |tab| -%>
  <span<%= selected == tab[:label] ? " class=selected" : "" %>><a href="<%= tab[:url] %>"><%= tab[:label] %></a></span>
<% end -%>
</div>

Project3/app/views/tabs/show2.html.erb
<h2>Hey, here are some tabs:</h2>
<%= render partial: "tabs", locals: { tabs: @tabs_1, selected: @tabs_1.second[:label] } %>
<%= render partial: "tabs", locals: { tabs: @tabs_2, selected: @tabs_2.first[:label] } %>